config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  
  get 'top/main'
  get 'top/login', to: 'top#login_form'
  post 'top/login'
  get 'top/logout'
  root 'top#main'
  #root 'cards#index'  
  
  resources :users
  resources :cards do
    member do
      patch :update_memo
    end
  end

  get 'get_image/:id', to: 'images#get_image'
  #get 'cards', to: 'cards#index', as: 'card_with_view_type'
  #get 'cards_with_view_type', to: 'cards#index', as: 'card_with_view_type'  # card_with_view_type_path
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :memos
    
  def self.search(query)
    if query.present?
      where("company LIKE ? OR name LIKE ? OR position LIKE ? OR license LIKE ? OR mail LIKE ? OR tell LIKE ? OR company_adress LIKE ? OR memo LIKE ?", 
      "%#{sanitize_sql_like(query)}%", "%#{sanitize_sql_like(query)}%", "%#{sanitize_sql_like(query)}%", "%#{sanitize_sql_like(query)}%",
      "%#{sanitize_sql_like(query)}%", "%#{sanitize_sql_like(query)}%", "%#{sanitize_sql_like(query)}%", "%#{sanitize_sql_like(query)}%")
    else
      all
    end
  end
  
  # ユーザーの専用メモを取得
  def memo_for(user)
    (JSON.parse(memo || "{}"))[user.id.to_s]
  end
  
  # ユーザー専用メモを更新
  def update_memo_for(user, content)
    current_memo = JSON.parse(memo || "{}")
    current_memo[user.id.to_s] = content
    update(memo: current_memo.to_json)
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :cards
    
    validates :my_company, presence: true
    validates :my_name, presence: true
    validates :pass, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:login_uid]) if session[:login_uid]
  end
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  #def index
  #  if params[:view_type] == 'mypage'
  #    @view_type = params[:view_type]
  #    card_ids = params[:card_ids].split(',')
  #    @cards = Card.search(params[:query]).where(id: card_ids).order(:created_at)
  #    render 'index_mypage'
  #  else
  #    @cards = Card.search(params[:query]).order(:created_at)
  #    render 'index'
  #  end
  #end
  
  def index
    @mypage = params[:mypage] == 'true'
  
    if current_user
      if @mypage
        # ログインしているユーザーが作成したカードのみを表示
        @cards = Card.search(params[:query])
                     .where(user: current_user)
                     .order(:created_at)
      else
         # 会社ページの場合、ユーザーの所属する会社に所属する全ユーザーのカードを表示
        @cards = Card.search(params[:query])
                     .joins(:user) # ユーザーとカードを結合
                     .where(users: { my_company: current_user.my_company }) # ユーザーの会社が一致
                     .order(:created_at)
      end
    else
      # ログインしていない場合は空の結果を返す
      @cards = Card.none
    end
  
    render 'index'
  end

  
  def new
    @card = Card.new
  end
  
  #def create
  #  c = Card.new(card_params)
  #  c.user = User.find_by(my_name: session[:login_uid])
  #  if c.save
  #    redirect_to card_with_view_type_path(params[:id], 'mypage')
  #  else
  #    render 'new'
  #  end
  #end
  
  def create
    @card = Card.new(card_params)
    @card.user = User.find_by(id: session[:login_uid])
    
    if @card.save
      redirect_to cards_path(mypage: true)
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy
    @card = Card.find(params[:id])
    if @card.destroy
      redirect_to cards_path(mypage: true)
    else
      redirect_to cards_path(mypage: true)
    end
  end
  
  def show
    @card = Card.find(params[:id])
    @mypage = params[:mypage] == 'true'
    @user_memo = @card.memo_for(current_user)
    render 'show'
  end
  
  def edit
    @card = Card.find(params[:id])
  end
  
  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      redirect_to card_path(@card, mypage: params[:mypage])
    else
      render 'edit'
    end
  end
  
  def get_image
    image = Card.find(params[:id])
    send_data image.file, disposition: :inline, type: 'image/png'
  end

  before_action :set_card, only: [:show, :edit, :update, :update_memo, :destroy]

  def update_memo
    @card.update_memo_for(current_user, params[:memo])
    redirect_to card_path(@card, mypage: params[:mypage])
  end
end

private

def card_params
  params.require(:card).permit(:company, :name, :position, :license, :mail, :tell, :company_adress, :image)
end

def set_card
    @card = Card.find(params[:id])
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        if session[:login_uid]
            redirect_to cards_path
        end
    end
    
    def login_form
        #ログイン画面の表示
    end
    
    def login
        user = User.find_by(my_name: params[:my_name])
        if  user && user.pass == params[:pass]
            session[:login_uid] = user.id  #params[:my_name]
            redirect_to top_main_path
        else
            redirect_to top_login_path
        end
    end

    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    c = User.new(my_company: params[:user][:my_company], 
                 my_name: params[:user][:my_name], 
                 pass: params[:user][:pass])
    if c.save
      redirect_to top_login_path
    else
      @user = c
      render 'new', status: :unprocessable_entity
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user =User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(my_company: params[:user][:my_company],
                 my_name: params[:user][:my_name],
                 pass: params[:user][:pass])
    redirect_to users_path
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/edit.html.erb
<div class = "header">
  <div class="title">
    <h3>編集</h3>
  </div>
  <div class="nav">
    <%= link_to "戻る", card_path(@card, mypage: params[:mypage]) ,class: "button"%>
    <%= link_to 'ログアウト', top_logout_path ,class: "button"%>
  </div>
</div>

<%= form_with model: @card, local: true do |c| %>
  <body>
    <div class="syosai">
      <p><%= c.label :company, '会社名' %>：<%= c.text_field :company , class: "field"%></p>
      <p><%= c.label :name, '氏名' %>：<%= c.text_field :name , class: "field"%></p>
      <p><%= c.label :position, '役職(肩書き)' %>：<%= c.text_field :position , class: "field"%></p>
      <p><%= c.label :license, '資格' %>：<%= c.text_field :license , class: "field"%></p>
      <p><%= c.label :mail, 'メールアドレス' %>：<%= c.text_field :mail , class: "field"%></p>
      <p><%= c.label :tell, '電話番号' %>：<%= c.text_field :tell , class: "field"%></p>
      <p><%= c.label :company_adress, '会社住所' %>：<%= c.text_field :company_adress , class: "field"%></p>
      <p><%= c.label :image, '名刺画像' %>：<%= c.file_field :image%></p>
      <%= c.submit '更新' ,class: "button" %>
    </div>
  </body>
<% end %>

app/views/cards/index.html.erb
<body>
  <header>
    <div class ="nav">
      <%= link_to @mypage ? '会社ページ' : 'マイページ', cards_path(mypage: !@mypage), class: "button" %>
      <%= link_to '新規追加', new_card_path(mypage: @mypage), class: "button" if @mypage %>
      <%= link_to 'ログアウト', top_logout_path, class: "button" %>　
    </div>
    <div class ="title">
      <h3><%= @mypage ? 'マイページ' : '会社ページ' %></h3>
    </div>
  </header>

  <div class = "cardmain">
    <h1><%= @mypage ? '登録名刺' : '名刺' %></h1>
    <br>
    <%= form_with(url: cards_path, method: :get, local: true) do |f| %>
      <%= f.label :query, "検索" %>
      <%= f.text_field :query, value: params[:query], placeholder: "キーワード入力" %>
      <%= hidden_field_tag :mypage, @mypage %>
      <%= f.submit "検索" %>
    <% end %>

    <% if @cards.any? %>
      <h2>検索結果</h2>
      <ul>
        <% @cards.each do |c| %>
          <li>
            <strong><%= c.company %></strong><br>
            名前: <%= c.name %><br>
            <%= link_to '詳細', card_path(c, mypage: @mypage) %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>該当する結果が見つかりませんでした。</p>
    <% end %>
  </div>
</body>

app/views/cards/new.html.erb
<body> 
  <header>
    <div class="title">
      <h3>名刺追加</h3>
    </div>
    <div class ="nav">
      <%= link_to "戻る", cards_path(mypage: params[:mypage]) ,class: "button"%>
      <%= link_to 'ログアウト', top_logout_path ,class: "button"%>
    </div>
  </header>

<%= form_with model: @card, local: true do |c| %>
    <div class="syosai">
      <p><%= c.label :company, '会社名' %>：<%= c.text_field :company , class: "field"%></p>
      <p><%= c.label :name, '氏名' %>：<%= c.text_field :name , class: "field"%></p>
      <p><%= c.label :position, '役職(肩書き)' %>：<%= c.text_field :position , class: "field"%></p>
      <p><%= c.label :license, '資格' %>：<%= c.text_field :license , class: "field"%></p>
      <p><%= c.label :mail, 'メールアドレス' %>：<%= c.text_field :mail, class: "field" %></p>
      <p><%= c.label :tell, '電話番号' %>：<%= c.text_field :tell, class: "field" %></p>
      <p><%= c.label :company_adress, '会社住所' %>：<%= c.text_field :company_adress, class: "field" %></p>
      <p><%= c.label :image, '名刺画像' %>：<%= c.file_field :image %></p>
      <%= c.submit '送信',class: "button" %>
    </div>
  </body>
<% end %>

app/views/cards/show.html.erb
<body>
  <header>
    <div class="title">
      <h3>名刺詳細</h3>
    </div>
    <div class ="nav">
      <%= link_to 'ログアウト', top_logout_path ,class: "button"%>
    </div>
  </header>
  <div class = "cardmain"> 
    <p>会社名：<%= @card.company %></p>
    <p>氏名：<%= @card.name %></p>
    <p>役職(肩書き)：<%= @card.position %></p>
    <p>資格：<%= @card.license %></p>
    <p>メールアドレス：<%= @card.mail %></p>
    <p>電話番号：<%= @card.tell %></p>
    <p>会社住所：<%= @card.company_adress %></p>
    
    <% if @card.image.try(:attached?) %>
      <p>名刺画像：<%= image_tag url_for(@card.image), alt: "名刺画像", width: 200 %></p>
    <% else %>
      <p>画像がありません。</p>
    <% end %>
    
    <h3>メモ</h3>
    <%= form_with url: update_memo_card_path(@card), method: :patch, local: true do |f| %>
      <%= text_area_tag :memo, @user_memo, rows: 5, placeholder: "ここにメモを入力してください" %>
      <%= f.submit "メモを保存" %>
    <% end %>
    
    <div class="button_container">
      <%= link_to '戻る', cards_path(mypage: @mypage), class: "button"%>
      
      <% if @mypage %>
        <%= link_to '編集', edit_card_path(@card, mypage: params[:mypage]), class: "button" %>　<%= link_to '削除', card_path(@card), data: { turbo_method: :delete } ,class: "button"%>
      <% end %>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NameCard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login_form.html.erb
<%= form_with url: '/top/login', method: :post, local: true do |f| %>
  <body>
    <div class="top">
    <h1>ログイン</h1>
    </div>
    <br>
    <div class="input">
    <%= f.label :my_name, '名前' %>
    <%= f.text_field :my_name, class: "field" %>
    <br>
    <%= f.label :pass, 'パスワード' %>
    <%= f.text_field :pass, class: "field" %>
    <br>
    <div class="buttons">
    <%= f.submit 'ログイン',class: "button" %>
    </div>
  </body>  
<% end %>

app/views/top/main.html.erb
<%= form_with url: '/top/main', method: :post, local: true do |f| %>
  <body>
    <div class="top">
    <h1>名刺マネージャー</h1>
    </div>
    <br>
    <div class="buttons">
    <%= link_to "新規登録" ,new_user_path, class: "button" %>
    <%= link_to "ログイン" ,top_login_path, class: "button" %>
    </div>
    <br>
    <div class="main">
    <h2>営業マンや新入社員の方々におすすめ</h2>
    <p>必要事項を入力するだけで持っている名刺情報を安全に一括管理</p>
    <p>詳細には名刺の基本情報や自分だけが分かる特徴をメモ！</p>
    <p>検索機能で必要な名刺情報をすぐに確認できます</p>
    </div>
  </body>
<% end %>

app/views/top/top_page.html.erb
<%= form_with url: '/top/top_page', method: :post, local: true do |f| %>
    <h1>名刺マネージャー</h1>
    <%= link_to '新規登録'%>
    <%= link_to 'ログイン'%>
    <p>説明</p>
<% end %>

app/views/users/edit.html.erb
<%= form_with model: @user, local: true do |f| %>
　　<h1>編集</h1>
　　<p>
　　<%= f.label :my_company, '会社名' %>
    <%= f.text_field :my_company %>
    </p>
    <p>
    <%= f.label :my_name, '名前' %>
    <%= f.text_field :my_name %>
    </p>
    <p>
    <%= f.label :pass, 'パスワード' %>
    <%= f.text_field :pass %>
    </p>
    <%= f.submit '保存' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |e| %>
    会社名：<%= e.my_company %>
    名前：<%= e.my_name %>
    <%= link_to "詳細", user_path(e) %>
    <br>
<% end %>
<%= link_to "ログアウト", top_logout_path %>

app/views/users/new.html.erb
<%= form_with model: @user, url: users_path do |f| %>
  <body>
    <div class="top">
    <h1>新規登録</h1>
    </div>
    <br>
    <div class="input">
    <%= f.label :my_company, '会社名' %>
    <%= f.text_field :my_company, class: "field" %>
    <br>
    <%= f.label :my_name, '名前' %>
    <%= f.text_field :my_name, class: "field" %>
    <br>
    <%= f.label :pass, 'パスワード' %>
    <%= f.text_field :pass, class: "field" %>
    <br>
    <div class="buttons">
    <%= f.submit '登録' ,class: "button"%>
    </div>
  </body>
<% end %>

<% if @user.errors.any? %>
  <div class="error">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
    <p>会社名：<%= @user.my_company %></p>
    <p>名前：<%= @user.my_name %></p>
    <p>パスワード：<%= @user.pass %></p>

<%= link_to "編集", edit_user_path %>

<%= link_to "ユーザ一覧にもどる", users_path %>

<%= link_to "削除", user_path(@user), data: {turbo_method: :delete} %>